<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Bridge.Storage</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Parquet.Net" Version="4.24.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Bridge.Core\Bridge.Core.csproj" />
  </ItemGroup>
</Project>
